### ISSUE TITLE
关于缓存Component的疑惑

### ISSUE THREAD

**Issue by withparadox2** [zack24q/vue-navigation#1]
你好，有个问题需要咨询一下。我看了下代码，你是根据path为component构造了一个name，真正缓存组件实例还是靠keep-alive。问题是，keep-alive在缓存时并未使用到name这个属性来计算key，如何保证一个component可以缓存多份实例呢？
```
var key = vnode.key == null
    // same constructor may get registered as different local components
    // so cid alone is not enough (#3269)
    ? componentOptions.Ctor.cid + (componentOptions.tag ? ("::" + (componentOptions.tag)) : '')
    : vnode.key;
if (this.cache[key]) {
    vnode.componentInstance = this.cache[key].componentInstance;
} else {
    this.cache[key] = vnode;
}
```

**Comment by zack24q** [comment]
你好。
这个库的思路是：

- 使用vue中keep-alive来缓存组件；

- 记录页面的导航记录；

- 使用keep-alive的include属性来控制组件的缓存与否；

从而实现缓存页面的功能。

官方文档中keep-alive的include属性会匹配组件的name属性，如果不存在name，则匹配局部注册名称，但好像在vue-router的环境下，是没有局部注册名称的，只能为组件补全name属性来通知keep-alive。只有name属性的话，keep-alive应该是无法为一个component缓存多份实例的。

另外，这个库的目的是帮助缓存导航的路由页面，应该不会有需要为一个页面缓存多个实例的需求吧？

**Comment by withparadox2** [comment]
好的，我知道了，非常感谢。
