### ISSUE TITLE
vue-router的replace失效

### ISSUE THREAD

**Issue by Jiiiiiin** [zack24q/vue-navigation#11]
你好，昨天反馈的问题不是很清晰，不好意思；
下面说一下今天实际使用中遇到的问题：
### 案例：A->B->C 3个页面跳转，B是一个确认页面，业务需求，从C返回的时候不需要返回到B，而是直接返回到A，之前我们项目一直使用[vue-router的router.replace(location)或者<router-link :to="..." replace>](https://router.vuejs.org/zh-cn/essentials/navigation.html)的方式，达到预期效果，但是加入vue-navigation插件之后，上面的属性（或者说预期效果就失效了）；

在补充一个，上面的测试是没有使用navigation标签包裹的测试，如果使用的这个标签，整一个页面都会变白。其实我的需求只是，插件帮我监控页面的流转，然后给我响应的事件通知，【同时在页面跳转时会提交 navigation/FORWARD 或 navigation/BACK 或 navigation/REFRESH。】，因为如果我直接在项目中做的话，会把这一块的状态修改分散开，不是很好，所以我用了该插件。

有描述的不到位的，多多包涵。

**Comment by zack24q** [comment]
`router.replace`的问题我知道，需要等`vue-router`官方支持一个特性才行，已经有人提过这个[issues](https://github.com/vuejs/vue-router/issues/1620)了，或许等空一些我就会去提PR来解决这个问题。

关于添加`navigation`后空白，能在[JSFiddle](https://jsfiddle.net/)上用重现，然后发我链接吗？

**Comment by Jiiiiiin** [comment]
@zack24q  【关于添加navigation后空白】问题重现，有点不太好搞，各种原因，目前我们还是用官方的【keep-alive】了，其实我们做的因为是银行应用，所以目前有些限制，对于组件缓存这块需求不是很高。
如果能把replace问题解决，其实我这边就够用了，有时间会拜读一下您的源码，也会持续关注这个问题。
谢谢恢复。

**Comment by zack24q** [comment]
请升级到1.1.0

**Comment by Jiiiiiin** [comment]
thks!

**Comment by moshanghan** [comment]
问一下，关于replace的问题现在解决了吗？我用的是1.1.1版本

**Comment by zack24q** [comment]
是的

**Comment by moshanghan** [comment]
A页面通过replace跳转到B页面，B页面通过push，跳转到A页面，如此循环往复几次，
结果通过浏览器物理返回的时候，B页面可以正常的显示，但是A页面的title被缓存了起来，显示在B页面上
这是怎么回事？

**Comment by moshanghan** [comment]
replace依然有问题

**Comment by despire1119** [comment]
replac依然有问题

**Comment by a798032825** [comment]
replac依然有问题
