### ISSUE TITLE
有些组件会触发render，导致页面出现问题

### ISSUE THREAD

**Issue by x007xyz** [zack24q/vue-navigation#12]
vux的datetime，mint-ui的datetime组件，还有我自己写的组件，使用时，会导致navigation组件updated和render执行两次，然后页面空白。使用keep-alive不会出现这个问题，keep-alive的render只执行一次。
[http://pan.baidu.com/s/1pLkaIuR](使用我的组件的demo)

**Comment by zack24q** [comment]
请升级到1.1.0

**Comment by xsdlr** [comment]
v1.1.0有bug， 修复#13

**Comment by x007xyz** [comment]
谢谢
