### ISSUE TITLE
无法获取滚动条位置

### ISSUE THREAD

**Issue by moshanghan** [zack24q/vue-navigation#15]
感谢，帮了大忙，
但是，之前列表框，是根据滚动条的的滚距离来为顶部的搜索框设置渐变色，现在拿不到body滚动条的具体位置了，请问如何获取滚动条具体位置？

**Comment by zack24q** [comment]
是加了vue-navigation之后导致的吗？

**Comment by zack24q** [comment]
可是vue-navigation并没有添加滚动容器，只添加了vue-navigation库吗？是不是照着demo里写的，加了其他的标签和样式？

**Comment by moshanghan** [comment]
这是个商城的项目，不可能只引入vue-navigation一个库，也不是在写demo，但是之前是可以拿到滚动条高度的，引入vue-navigation之后就不行了，当然我对page.vue做了一些调整，page的高度不是100%而是屏幕的高度，因为有个推荐列表在首页的最下面，目前还在找原因

**Comment by zack24q** [comment]
噢，你用了demo中的page.vue是吧，里面使用的滚动容器是content
```
<div class="content" @scroll="scroll" ref="content">
      <slot></slot>
</div>
```
所以需要去取这个element的scrollTop

**Comment by moshanghan** [comment]
同样的，拿不到，一直是0

**Comment by zack24q** [comment]
你对page.vue做了调整，滚动容器可能不是这个了，我建议你一层一层找一下滚动容器究竟是哪个元素，这个应该和vue-navigation无关，关闭问题了
