### ISSUE TITLE
你好，页面被缓存了，重新进入也不会重新加载

### ISSUE THREAD

**Issue by ifredom** [zack24q/vue-navigation#17]
比如从主页A ，进入列表B，再进入详情C
返回2次到A,再进入B， B不会重新加载。

**Comment by zack24q** [comment]
请给重现方式，线上的example里是会重现加载的

**Comment by ifredom** [comment]
具体使用是：
**mai.js**

import Navigation from './assets/lib/navigator/index' // 导航
const router = new VueRouter({
    mode: 'hash',
    routes,
    // linkActiveClass: 'router-active',
    strict: process.env.NODE_ENV !== 'production',
    scrollBehavior(to, from, savedPosition) {
        if (savedPosition) {
            return savedPosition
        } else {
            if (from.meta.keepAlive) {
                from.meta.savedPosition = document.body.scrollTop;
            }
            return { x: 0, y: to.meta.savedPosition || 0 }
        }
    }
})
Vue.use(Navigation, { router, store })

**app.vue**

	<transition :name="transitionName">
		<navigation>
			<router-view class="child-view"></router-view>
		</navigation>
	</transition>

**Comment by ifredom** [comment]
恩，线上的demo没问题，跑过。
使用的vue-cli，在npm run dev模式下，测试时发现只要页面呗缓存了一次，再次不会重新加载

**Comment by zack24q** [comment]
能在[http://jsbin.com/](http://jsbin.com/)里用简单的代码重现，然后把地址发出来吗？单从这个代码里看不出可能的原因

**Comment by ifredom** [comment]
只有再项目里会重新，可以给个QQ号吗

**Comment by zack24q** [comment]
413168893
