### ISSUE TITLE
关于新增完返回列表

### ISSUE THREAD

**Issue by cm2316** [zack24q/vue-navigation#18]
新增完数据，返回列表的时候要刷新数据，要怎么处理比较好。window.history.back(),好像不能带参数。
现在有用事件搞通知的，还有store存参数。有没有比较简单的方法？

**Comment by zack24q** [comment]
返回后组件会调用`activated`钩子，可以在里面判断并刷新数据，这样就不用为了这一个组件去全局注册事件

**Comment by cm2316** [comment]
就是activated里面怎么判断要刷新，因为有点左上角返回（这个情况是不刷新的），有点保存按钮返回（这个情况是要刷新的）

**Comment by zack24q** [comment]
复杂的应用，推荐在vuex中操作数据；
比如你这种情况，可以这样设计：
- 列表需要的数组A从store里取
- 点击保存时更新store里的数组A

列表的数据会和store里的数组同步，不用事件或传参数来通信，也不用加`activated`钩子

**Comment by cm2316** [comment]
好的。我就是想知道是不是有更简单的方法。
