### ISSUE TITLE
用 on绑定事件的重复问题！！！

### ISSUE THREAD

**Issue by DaDaDaDaDaBocai** [zack24q/vue-navigation#22]
问一下 我在某个页面用 
this.$navigation.on('back', (to, from) => {
        console.log('back to', to, 'from ', from)
})
绑定事件,
那么在每个页面返回的时候 都还会执行这个方法，用once 又只能执行一次，off 去除的话,下次又失效了,请问怎么解决这个问题？
因为我要在某些特定页面在返回的时候 把loading的按钮重置为正常

**Comment by zack24q** [comment]
`this.$navigation`绑定事件的使用场景是全局级别的，如果某些特定页面需要在返回时执行代码，可以直接使用vue的组件生命周期钩子，比如：`activated`、`deactivated`、`destroy`。

[示例代码](https://github.com/zack24q/vue-navigation/tree/v1.1.2/examples/src/pages)，在从路由`/list`返回`/`时，`List`组件的`destroyed`会被触发，然后返回到`/`后，`Index`组件的`activated `也会被触发，选择你需要的钩子编写代码即可。
