### ISSUE TITLE
页面通过replace，跳转，title被缓存

### ISSUE THREAD

**Issue by moshanghan** [zack24q/vue-navigation#24]
搜索页面通过replace跳转到列表页面，列表页面通过push，跳转到搜索页面，如此循环往复几次，
结果通过浏览器物理返回的时候，列表页面可以正常的显示，但是搜索页面的title被缓存了起来，间隔的显示在列表页面上
这是怎么回事？

**Comment by zack24q** [comment]
能不能写个例子重新一下，然后给个链接？只有描述不好判断问题

**Comment by moshanghan** [comment]
不好意思，另一个开发人员单独缓存了title，没有问题的
