### ISSUE TITLE
1.1.2这个版本引入了lodash中的isEqual方法，文件尺寸瞬间增大了十几k。

### ISSUE THREAD

**Issue by fa-ge** [zack24q/vue-navigation#25]
![image](https://user-images.githubusercontent.com/6771881/31399106-c2d6e034-adb0-11e7-93e0-ffd379072611.png)
这是引入1.1.2版本后加载的lodash的尺寸。改成1.1.1后就不会有lodash这个依赖了。看了一下是按需引入lodash的问题。

**Comment by zack24q** [comment]
请更新到v1.1.3，移除了lodash，改为自己实现
