### ISSUE TITLE
作者能否在传入store内暴露出前进后退的state

### ISSUE THREAD

**Issue by yhZhouYh** [zack24q/vue-navigation#26]
因为，想根据路由前进后退来写不同专场效果 遂在navigator.js里 state内加入了 direction方便获取。。

![image](https://user-images.githubusercontent.com/13265388/31430133-8d67f468-aea2-11e7-90bb-c91b21995064.png)
这样 我方便 在计算属性内获取当前 路由方向
![image](https://user-images.githubusercontent.com/13265388/31430210-c833f858-aea2-11e7-81c7-c803e3ec2127.png)

**Comment by zack24q** [comment]
由插件来改`store`里的值不是很好，最好的方式就是像你这样，由开发者自己来改值

推荐你在自己的`store.js`里来做这件事，可以参考[代码](https://github.com/zack24q/vue-navigation/blob/master/examples/src/store/index.js#L10)
