### ISSUE TITLE
url添加了VNK参数之后，每次访问项目首页的时候因为参数不同 导致每次都是请求资源 而不是加载缓存。

### ISSUE THREAD

**Issue by Honey-hoo** [zack24q/vue-navigation#29]
- url添加了VNK参数之后，每次访问项目首页的时候因为参数不同 导致每次都是请求资源 而不是加载缓存。这个问题有解吗

**Comment by zack24q** [comment]
目前无解
你的项目应该也是单页应用的架构对吧；url变化后，会重新加载html文件，但是单页的html文件是很小的，js和css并不会重新加载，应该问题不大吧

**Comment by Honey-hoo** [comment]
是的呢 用查尔斯代理查看之后 发现虽然URL变化 但是js和css名称没有发生变化 并没有重新请求加载 而是读取缓存的。谢谢
