### ISSUE TITLE
请问怎么指定b页面缓存

### ISSUE THREAD

**Issue by xcsweb** [zack24q/vue-navigation#3]
请问怎么指定b页面缓存，其他页面都不需要缓存，还有，你这个必须使用vuex吗

**Comment by zack24q** [comment]
如果需求是缓存指定的页面，而不是根据路由状况来缓存页面，那就不需要使用这个库，直接使用[keep-alive](http://cn.vuejs.org/v2/api/#keep-alive)即可。另：这个库可以不搭配vuex使用
