### ISSUE TITLE
A->B , B页面有操作，返回时需要更新A页面的时候。怎么刷新A的页面

### ISSUE THREAD

**Issue by Honey-hoo** [zack24q/vue-navigation#31]
针对这个问题我具体描述一下，比如地址列表页，点击一条地址可以进去进行修改和删除操作，由于用了vue-navigation ，列表页拉取数据的方法 我是在mounted里面执行的。使用了vue-navigation之后，从地址列表页进入地址编辑页 进行完编辑【保存】或者【删除】之后，我会使用history.go(-1)返回列表页。但是这个时候由于返回之后列表页直接读的是缓存，显示编辑或者删除的那条地址并没有改变。
还有很多类似这种有数据更新的页面 返回就会出现类似这样没有重新拉取数据更新的页面，然后我发现 把页面数据请求放在activated这个方法里 返回列表页就会刷新。
请问作者大大，在activated这个方法里做数据请求 是这类问题的最佳解决方案吗？

**Comment by zack24q** [comment]
是的
因为将组件缓存了，没有销毁，所以切回去时不会触发mounted，但是会触发activated
