### ISSUE TITLE
每次切换页面的时候，被缓存住的页面里面请求的api都会再次去请求，这个该怎么处理啊

### ISSUE THREAD

**Issue by sessplus** [zack24q/vue-navigation#32]

**Comment by zack24q** [comment]
被缓存住的页面里面请求，是怎么触发的？

**Comment by ericzhao1979** [comment]
我也遇到这个问题。发现是因为navigation嵌套引起的。似乎我们的navigation组件不支持嵌套

**Comment by zack24q** [comment]
目前navigation是不支持嵌套的，欢迎PR

**Comment by Jialufeng** [comment]
遇到同样问题，在a页面  有个b按钮，当从a页面跳到c页面，在返回到a页面点击b按钮的时候，会执行两次ajax请求，不从a跳到c 就只请求一次，应该是被缓存了，，，，

**Comment by Jialufeng** [comment]
把ajax  放在了  beforeRouteEnter(to, from, next) {} 函数里，目前是解决问题了。
