### ISSUE TITLE
replace时无法缓存

### ISSUE THREAD

**Issue by ericzhao1979** [zack24q/vue-navigation#34]
我不清楚通常实现tab的最佳实践，我们是用replace实现的。
结果在tab间切换时，缓存无法工作

**Comment by zack24q** [comment]
这个库的目的是去自动缓存历史记录中的页面，replace的页面并不会进入到历史记录里，所以不会缓存，tab切换的缓存，需要自己来实现
后面我会考虑把缓存的实现单独做一个库，来节省那些需要定制缓存的开发者的事件
