### ISSUE TITLE
关于UC浏览器内核报错的问题

### ISSUE THREAD

**Issue by lmasdata** [zack24q/vue-navigation#36]
你好，
      首先非常感谢您的vue-navigation,解决了项目中的很大问题。
      我们正在使用vue开发一款钉钉应用，但是这个应用安卓版的钉钉上是白屏，经过调试是因为Object.assign不兼容。问了下他们的浏览器内核是基于UC的。
     然后发现vue-navigation也用了Object.assign，请问，是否有什么解决方案？或者更新计划。

**Comment by zack24q** [comment]
使用的最新版的吗？项目的babel配好了的，应该是可以兼容较老的浏览器的
