### ISSUE TITLE
不支持 router 传参数？ 只能query传参数？

### ISSUE THREAD

**Issue by ghost** [zack24q/vue-navigation#37]
不支持 router 传参数？ 只能query传参数？

感觉不方便呀， 有写参数量比较打，不想走query

**Comment by lyh2668** [comment]
@wallini 传递params后退则无法获取参数了，会有问题，复杂的参数还是通过vuex传递比较好

**Comment by zack24q** [comment]
传参数和这个库无关，是`vue-router`负责的
