### ISSUE TITLE
【BUG】使用路由懒加载 报错

### ISSUE THREAD

**Issue by showbestriven** [zack24q/vue-navigation#4]
![image](https://user-images.githubusercontent.com/25165547/27373379-9de3fc66-569a-11e7-9b2f-fd33224ce847.png)

![image](https://user-images.githubusercontent.com/25165547/27373450-df352190-569a-11e7-9554-a4e29c65a5b1.png)

问题：
用作者你的demo 改成路由懒加载 会报如上错误 不使用则不会报错

**Comment by zack24q** [comment]
现已支持异步组件，请更新到0.2.2

**Comment by showbestriven** [comment]
@zack24q
有个问题很奇怪 我更想到0.22版本 发现你的组件只有kee-alive 缓存的效果了。 
我去点你github上的demo发现没问题
然后我从github上档下你的项目运行 发现异步加载也只有kee-alive 缓存的效果 并没有前进重新加载 后退不加载的 效果， 随机数并没有变化 但是去掉异步加载没问题了

**Comment by showbestriven** [comment]
同一个浏览器下

**Comment by zack24q** [comment]
keep alive会读取组件的name来进行缓存，在开发环境下，keep alive获取到的组件始终是没有设置好name的组件，但是打完包后在生产环境下，keep alive获取到的组件就是已经设置好name的组件了，我猜想可能是开发环境下异步组件的加载时机和打完包后不一样的缘故。
我建议你为绑到路由上的所有组件设置上name

**Comment by showbestriven** [comment]
node 版本  v6.10.2
npm  3.10.10

**Comment by showbestriven** [comment]
但是我用作者你github上的项目 运行起来 也是不能达到预期的效果。 我先去试一试打包后看看

**Comment by zack24q** [comment]
对，我就是指本地dev开发的时候，明明在异步组件加载完成后设置了name后再传出去，但是在keep alive里拿到的始终是不带name的组件，但是build出来的项目就没有这个问题

**Comment by zack24q** [comment]
这个问题是有点奇怪，dev时异步组件的name设置不上，我再去研究一下能不能解决

**Comment by showbestriven** [comment]
是的 这个问题 确实很奇葩  我自己原本是通过在route的meta里设置一个标示 来确认是否缓存页面 但是这么做 操作有点繁琐

**Comment by showbestriven** [comment]
而且作者你可以 将 前进 后退  刷新 的事件 emit() 出来哦 提供下监听事件

**Comment by zack24q** [comment]
开发时候name设置不上的原因找到了，可以解决；
目前的版本的话，配合vuex使用，是可以获取到事件的，组件上的事件绑定下个版本会加上

**Comment by zack24q** [comment]
@showbestriven v0.3.0 添加了事件

**Comment by showbestriven** [comment]
@zack24q  嗯 已经把原本的页面切换动画的判断迁移到这个事件里来了。 
其实我还是比较 关注 ‘开发时候name设置不上的原因找到了，可以解决’ 这个问题 ：}

**Comment by zack24q** [comment]
这个已经解决了，开发环境下，vue从组件的_Ctor属性里取值，build后没有这个属性，直接是从组件取值

**Comment by showbestriven** [comment]
嗯 已经测试成功 建议组件的监听事件上参数 from, to 能和vue-router 保持一致

**Comment by zack24q** [comment]
参考了建议，事件参数变为对象，包含了name与vue-router的路由信息，有break change，发布v0.4.0 #
