### ISSUE TITLE
不能保持 div 滚动条位置

### ISSUE THREAD

**Issue by wcldyx** [zack24q/vue-navigation#43]
其他的数据可以保存，但是就是不能保持div滚动位置，每次回退过来的时候，滚动条就回到顶部了，请问这个怎么解决

**Comment by shoung6** [comment]
@wcldyx vue router的history模式有保存滚动条位置的配置

**Comment by zack24q** [comment]
如果是容器overflow的滚动条，可以参考demo中的方式，自己封装一个基础组件
https://github.com/zack24q/vue-navigation/blob/v1.1.3/examples/src/components/Page.vue#L27
