### ISSUE TITLE
beforeDestory这个钩子函数进不去了？

### ISSUE THREAD

**Issue by 450671491** [zack24q/vue-navigation#48]
退出页面的时候，beforeDestroy这个钩子失去了作用？

**Comment by zrain** [comment]
@450671491 退出页面是指什么时候？ 如果只是两个被缓存的组件之间的切换的话，因为组件本身并没有被销毁所以不会触发 beforeDestroy& destroyed；

只有当 navigation本身被销毁的时候，会触发所有其缓存过的组件的beforeDestroy& destroyed的钩子函数

另外：如果业务有需要处理。
被缓存的页面在被切换的时候会触发如下两个钩子函数
https://cn.vuejs.org/v2/api/#activated
https://cn.vuejs.org/v2/api/#deactivated
