### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by nothinggift** [zack24q/vue-navigation#5]
项目中有类似的需求，我们也开发了类似的功能，但仍有很多问题，所以没有开源，主要有以下几个问题：
1，A-》B-》C-》D-》B
以上这种导航，在最后的B点，点击后退操作时，应该后退到A点
2，replace处理
3，依赖keep alive，不支持ssr（nuxt.js)
（以上已解决）
4，刷新操作不影响导航
5，打开中间页，仍可以后退到首页

**Comment by zack24q** [comment]
你想表达的意思是什么？ 4，5你们没有解决，想要讨论一下？
