### ISSUE TITLE
nuxt怎么使用

### ISSUE THREAD

**Issue by gotoin** [zack24q/vue-navigation#50]
谢谢

**Comment by gotoin** [comment]
@zack24q

**Comment by zack24q** [comment]
目前还不支持nuxt，欢迎PR

**Comment by gotoin** [comment]
@zack24q 我看了一下nuxt 源码，他的asyncData方法是在router.beforeEach执行的，也就是说他的数据获取是在路由跳转之前，想半天没找到好的解决方案。

**Comment by gotoin** [comment]
我尝试在back的时候，使用next(false)中止路由，然后使用redirec(nuxt 在使用redirect 时不再执行 asyncData等方法) 但这样一下history就乱了

**Comment by gotoin** [comment]
还有一个方案是把nuxt的导航守护直接干掉, 如果cache里有缓存，直接取缓存，没有就初始化的时候干掉的导航守护再重新执行一次，但这样有点恶心
