### ISSUE TITLE
使用了vue-navigation后，路由跳转不能使用params传参？

### ISSUE THREAD

**Issue by RisenMyth** [zack24q/vue-navigation#54]
在使用了vue-navigation后，params接收到的参数总是为空对象，在去除后一切正常，请问有没有什么解决方案？

**Comment by Droid43** [comment]
感觉这个框架作者已经没有维护了，我修复完这个问题marge请求都没反应[#53](https://github.com/zack24q/vue-navigation/pull/53)

**Comment by zack24q** [comment]
已合并，请更新到 v1.1.4
