### ISSUE TITLE
新特性：用 history.state.key 代替 vnk

### ISSUE THREAD

**Issue by masquevil** [zack24q/vue-navigation#55]
把 src/utils.js 的 getKey 返回值替换成 history.state.key，然后 genKey vnk 之类的东西就可以去掉了。也不需要 replaceState，避免钩子触发两次的问题

**Comment by masquevil** [comment]
哦对了，这两天发现可能依赖 vue 的某些版本，具体到哪个版本不清楚，只知道我的 demo 用 2.1.x 有问题，2.5.x 是可以的。

**Comment by masquevil** [comment]
关了，因为又发现了一些问题… 这个值目前还不能这么用

**Comment by wiwimouse** [comment]
@masquevil Recently, I consider maintain local history list in my work and discovered that `vue-router` will automatically push that key into history. It's seems to be unique. Could you provide more information why `history.state.key` isn't reliable? It's will be a great help to me! thanks!

**Comment by wiwimouse** [comment]
I found there's  issue about `history.state.key`. Anyone came here can refer to https://github.com/vuejs/vue-router/issues/1658
