### ISSUE TITLE
When used with vuex  state name is always undefined?

### ISSUE THREAD

**Issue by random-one** [zack24q/vue-navigation#6]
Can you please confirm this or it's me doing something wrong with the store? All my components have their names set and I tested without vuex and names appear properly.
Here is my vuex configuration (nothing special I think): 
```
import Vue from 'vue'
import Vuex from 'vuex'
import { mutations } from './mutations'
import { actions } from './actions'

Vue.use(Vuex)

const state = {
  routes: [],
}

export default new Vuex.Store({
  state,
  actions,
  mutations,
})
```

**Comment by zack24q** [comment]
Bug fixed, please update v0.5.0
Thanks for filing the issue
