### ISSUE TITLE
怎么直接打开历史的页面?

### ISSUE THREAD

**Issue by lifetin** [zack24q/vue-navigation#62]
比喻首页我加载了不少数据. 再点去B,C页面,
我要直接返回到首页,要怎么返回呢?
我这边用了roter.push('/')
这样是一步回到了首页,但是内容给重新加载了.有没有办法一步回到首页,首页的内容还存在?

**Comment by zack24q** [comment]
目前只能开发者记住首页在哪一级，然后返回
比如路由栈是首页->B-C，然后调用`history.go(-2)`就能返回到首页

**Comment by lifetin** [comment]
我这边解决方法时. 遍历所有roter, 检测name是不是首页, 是的就把url中的key提出来,在打开时候填上,这样一就带上了缓存了.

![55](https://user-images.githubusercontent.com/10474968/47889593-b1372d00-de85-11e8-8af2-eb18b26abc51.png)

**Comment by zack24q** [comment]
如果使用roter.push的话，你的路由栈就变成首页->B-C->首页了，返回的时候会有点奇怪的

**Comment by lifetin** [comment]
那不用roter.push,  用什么方式好一些?
我这边试了.加上KEY是跳到了首页了, 但是之后的历史没有了. 相当于我一步返回到首页了,

**Comment by zack24q** [comment]
使用`history.go()`
比如路由栈是首页->B-C，你可以遍历routes，查到首页距离当前路由有2级，就history.go(-2)返回就可以了

**Comment by lifetin** [comment]
经君一句提醒,如醍醐灌顶,瞬间茅塞顿开! 
感谢了!!!
