### ISSUE TITLE
使用了vue-navigation后 微信无法正确识别图片和二维码

### ISSUE THREAD

**Issue by delfws** [zack24q/vue-navigation#75]
使用了vue-navigation后，会导致ios设备微信无法正确识别图片和二维码，表现如下

![1022750247](https://user-images.githubusercontent.com/24715927/55546609-4626a680-5702-11e9-9e8a-5696b915b857.jpg)

![1047188789](https://user-images.githubusercontent.com/24715927/55546614-48890080-5702-11e9-99eb-9d4335a5e034.jpg)

只有一个保存图片选项

**Comment by tyler4400** [comment]
请问解决了吗？

**Comment by delfws** [comment]
> 请问解决了吗？

没有，已经放弃了
