### ISSUE TITLE
识别重复路由的探讨

### ISSUE THREAD

**Issue by ElderJames** [zack24q/vue-navigation#8]
我的项目里，主要是通过监听pushstate事件识别重复的路由
https://github.com/ElderJames/vue-router-storage

**Comment by zack24q** [comment]
首先明确一下讨论的内容——在浏览器中怎么判断是前进还是后退操作。
看了你的方案，你是在进入单页应用的时候，把每个路由加上key后重新pushState了一遍，根据key的大小来判断是前进还是后退。
这个思路很不错，但是代价是每次进入应用的时候，需要将每个路由重新pushState来为其添加key，网页的历史记录中就会出现非用户添加的重复路由。如果用户刷新过好几次，这个路由就会非常的长。并且在用户后退时，添加了根目录防止继续后退的特性来阻止用户访问到重复的路由。
**会添加许多重复的路由**与**阻止用户返回上一页**这两个代价有点大：
- 阻止了用户返回上一页，会导致用户无法按自己的意愿返回之前的其他网页
- 允许了用户返回上一页的话重复路由就会暴露出来了

具体还是要看使用场景了，我这边可能无法使用这个方法来判断前进后退。

_测试你的库的时候发现了一些问题，提在issues里了，希望越做越好。_

**Comment by ElderJames** [comment]
感谢你提的issue，让我发现了重大的bug。针对在这里的讨论，我需要解释一下。

**需要将每个路由重新pushState来为其添加key** 只是我的插件的**路由历史记录恢复功能**，跟判断前进后退没关系，判断的依据就是参考vue-router的**根据key的大小**来作为判断的条件，替换key的操作vue-router本身已经做好了。我的插件依赖vue-router的路由变化事件来触发判断，并且当路径相同时，通过监听pushstate事件来做补偿。

我想请教一下

> **会添加许多重复的路由**与**阻止用户返回上一页**这两个代价有点大

代价具体在哪里？是不是我的插件应该加上取消这两点的配置？

**Comment by zack24q** [comment]
如果没有路由历史记录恢复功能，刷新后key都不存在了，怎么判断前进还是后退？据我所知vue-router的事件和popstate事件都无法判断出前进或者后退行为的。

**Comment by ElderJames** [comment]
刷新后key还在history.state里的 :-)

**Comment by zack24q** [comment]
这个key可靠的话确实是一个判断前进后退的好方法，后面我会尝试下这种方案。
关于vue-router-storage项目的内容，还是在vue-router-storage的项目的issues里讨论吧，我开一个issues。

**Comment by zack24q** [comment]
研究了一下，使用key还是有局限性的，vue-router的hash模式没有使用`pushState`，所以state的key一直是`null`。还是要兼容pushState无法使用的情况，再研究有没有更好的判断前进后退的方案吧。

并且这个库目前不允许重复路由出现的原因，是在`keep-alive`的限制上，而不是技术上无法识别重复路由，举个例子：
当路由从A->B->C后，此时如果再前进到A，因为A的路由已经存在于`keep-alive`的`include`属性中，所以A页面不会重新生成，而是根据缓存生成。前进行为是要生成新的页面的，根据缓存生成不是开发者的意愿，所以目前就先限制了重复的路由，正在寻找有没有更好的方案。

**Comment by ElderJames** [comment]
是的，我的插件还只是依赖了history模式，其它模式需要再研究。

我打算增加一个识别刷新的判断，刷新就不重新加载前置路由。

**Comment by zack24q** [comment]
嗯，这样体验会好非常多。
其他模式下的判断有一个方案就是把这个key值放到url里去，会有一些侵入性。

**Comment by ElderJames** [comment]
放到url里不是个好主意，会影响到路由参数的。
我的想法是注入到route里，或者研究vue-router的相关机制。

**Comment by zack24q** [comment]
url中添加?router_key=xxx，这种不会影响路由结构的。

主要问题是历史记录是存在浏览器里，只能获取到URL和history，如果key不存储在history的state中，就只能存在URL中了。

**Comment by zack24q** [comment]
发布了1.0，将key存储在URL中，这样既能区分相同URL的不同页面实例，又能配合SessionStorage中存储的路由数组区分前进后退行为。

期待大家提出更好的方案。

**Comment by ElderJames** [comment]
很好，我会参考一下！
