### ISSUE TITLE
vue-router 3.x support

### ISSUE THREAD

**Issue by fairking** [zack24q/vue-navigation#87]
If I switch the vue-router version to the "^3.1.3" I got the following error:
```
Error: Redirected from "/page1?vnk=f733d010" to "/page2" via a navigation guard.
```
As I understand the vue-router complains about the repeating the same redirect twise:
Redirect 1: "/page2"
Redirect 2: "/page2?vnk=123"

Is there any 3.x support planned guys? If not can somebody recommend any similar package availabe on npmjs with vue-router 3.x support?

Error reference: https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards

Stackoverflow: https://stackoverflow.com/questions/62223195/vue-router-uncaught-in-promise-error-redirected-from-login-to-via-a

**Comment by hezhongfeng** [comment]
@fairking https://github.com/hezhongfeng/vue-page-stack

**Comment by fairking** [comment]
Thanks, I will give it a go.

**Comment by hezhongfeng** [comment]
@fairking I will support vue-router next when vue 3.x and vue-router next is realese,now U can closed this issue.
